version: '3.8'

services:
  backend:
    build: .
    container_name: pdf_converter_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/temporal_files
    environment:
      - ENV=development